// calculator 각 사이 값 마다 적용될 스타일을 지정한다
export const clusterStyle = [
	{
		width: "23px",
		height: "23px",
		boxShadow: "0 0 0 12px rgba(255, 255, 255, 0.7)",
		margin: "12px",
		background: "#3d3d3d",
		borderRadius: "50%",
		fontSize: "13px",
		color: "#fff",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		fontWeight: "600",
		lineHeight: "20px",
		zIndex: "9",
	},
	{
		width: "23px",
		height: "23px",
		boxShadow: "0 0 0 20px rgba(255, 255, 255, 0.7)",
		margin: "20px",
		background: "#3d3d3d",
		lineHeight: "20px",
		borderRadius: "50%",
		color: "#fff",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		fontWeight: "600",
		zIndex: "9",
	},
	{
		width: "23px",
		height: "23px",
		boxShadow: "0 0 0  40px rgba(255, 255, 255, 0.7)",
		margin: "40px",
		background: "#3d3d3d",
		borderRadius: "50%",
		color: "#fff",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		fontWeight: "600",
		lineHeight: "20px",
		zIndex: "9",
	},
];
